// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ChatGptExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ChatGptExtension.6c13a0fb-3ce5-4b6c-a3f0-3695956a5766";
        public const string Name = "ChatGptExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tural Mamedov";
        public const string Tags = "";
    }
}
