// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ChatGptExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ChatGptExtensionString = "12d172ad-2637-4896-b5bc-e7ae1397b278";
        public static Guid ChatGptExtension = new Guid(ChatGptExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MenuEditorGroup = 0x0001;
        public const int MenuViewGroup = 0x0002;
        public const int EditorMenu = 0x1030;
        public const int AddTestButtonCommand = 0x0100;
        public const int FindBugsButtonCommand = 0x0200;
        public const int OptimizeButtonCommand = 0x0300;
        public const int ExplainButtonCommand = 0x0400;
        public const int CompleteCodeButtonCommand = 0x0500;
        public const int ShowChatWindowCommand = 0x0600;
    }
}